#!/bin/bash
 
#SBATCH --job-name=nextflow_run
#SBATCH --cpus-per-task=25
#SBATCH --mem=200G
#SBATCH --time=6:00:00
#SBATCH --qos=6hours
#SBATCH --output=nextflow_run.o%j
#SBATCH --error=nextflow_run.e%j

# nextflow run main.nf -profile slurm_offline -entry PHILOSOPHER
# nextflow run main.nf -profile slurm_offline -entry RIBOTISH -N pozzan.noe@gmail.com -resume
#nextflow run main.nf -profile slurm_offline -entry MOCK
# Setting "-profile slurm_offline"
# is necessary bc slurm nodes are not online
# ATTENTION: the riboseq read names should not contain ".",
# apart from the ".fastq.gz"

nextflow run \
	main.nf \
	-profile slurm_offline \
	-resume \
	--notification true //\
	//--riboseq_reads /path/to/reads \
	//--proteomics_reads /path/to/spectra \
	//--


